Original notebook by Sem Vijverberg for the series 'Python skills for research in Hydrology' for the master Hydrology at the Vrije Universiteit Amsterdam (2019).

# Numpy, for loops, while loops, if statements

## Importing packages:


Python Packages (or modules) are built by experts in C++ or Python and can be loaded by using the import function. This way, python offers a fast langague and people can expand the possibilies of Python by making packages with extra functionality. 


## Numpy
Numpy is one of the core packages, I think almost all data science application and other (higher end) packages rely on numpy. The numpy package allows fast manipulation and handling of arrays (numpy.ndarray objects can be created which point to single and multi-dimensional arrays).

Loading a package/module:

In [ ]:
import numpy as np

Create a range of numbers, from 0 to 10 with steps of 1. Note the range is **to** 10 and not **to and including** 10.

In [ ]:
range_of_numbers = np.arange(0, 10, 1) 
range_of_numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Selecting data

In [ ]:
range_of_numbers[0] # first index, note Pythonic counting starts at 0

0

In [ ]:
range_of_numbers[1] # second index

1

In [ ]:
range_of_numbers[-1] # last index

9

In [ ]:
range_of_numbers[5:7] # selecting 5th to and including 6th index

array([5, 6])

In [ ]:
range_of_numbers[::-1] # reverse numpy array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
boolean_mask = range_of_numbers >= 5 # return True if value above and equal to 5
range_of_numbers[boolean_mask] # Use boolean mask to select data that meets the criteria 'values above and equal to 5'

array([5, 6, 7, 8, 9])

## For loop
With a for loop you can simply iteratively loop through each of the numbers in your list

In [ ]:
# Functionality for loop:
for i in range_of_numbers:
    # your code doing something with value of i
    # {
    y = i * 2
    print(y)
    # }
    # Your code repeats what is between curly brackets {} for all values i, i.e. all values in range_of_numbers. 

0
2
4
6
8
10
12
14
16
18


## While loop and if statement

In [ ]:
i = 0 
condition = True # start condition of while loop
# if condition becomes False, the while loop will stop, if that doesn't happen, it will go on forever! 
while condition == True:
    i += 1 # iteratively add 1 to value i
    print(i)
    # definite 'if statement' to be able to say when the while loop must stop. 
    if i == 4: # if i is equal to 4.
        condition = False

1
2
3
4


## More questions? Google!

If you have any questions, just use the right words for your google search. Knowing these basic object types and python functions, you should be able to find the answer to 90% of your questions!

### Some details 
- A 1-dimensional array, like the number_range in the example above, is actually very similar to a list, but the functionality is different. A large number of numpy array manipulation will not work on a list. Vice versa, the .append() function or .index() function will not work on an array. 
- From a mathematics point of view, a 1-d array is called a vector. 
- Similarly, a multi-dimensional array with dimensions (time, space), is also called a matrix.  